apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "task-tracker.fullname" . }}-backend
  labels:
    app: {{ include "task-tracker.fullname" . }}-backend
    {{- include "task-tracker.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: {{ include "task-tracker.fullname" . }}-backend
  template:
    metadata:
      labels:
        app: {{ include "task-tracker.fullname" . }}-backend
    spec:
      containers:
      - name: backend
        image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
        imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.backend.service.port }}
        envFrom:
        - configMapRef:
            name: {{ include "task-tracker.fullname" . }}-config
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "task-tracker.fullname" . }}-secret
              key: DB_PASSWORD
        resources:
          {{- toYaml .Values.backend.resources | nindent 10 }}
