apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "task-tracker.fullname" . }}-frontend
  labels:
    app: {{ include "task-tracker.fullname" . }}-frontend
    {{- include "task-tracker.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: {{ include "task-tracker.fullname" . }}-frontend
  template:
    metadata:
      labels:
        app: {{ include "task-tracker.fullname" . }}-frontend
    spec:
      containers:
      - name: frontend
        image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
        imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.frontend.service.targetPort }}
        resources:
          {{- toYaml .Values.frontend.resources | nindent 10 }}
