{{- if .Values.managedCert.enabled }}
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: taskmonitor-cert
  labels:
    {{- include "task-tracker.labels" . | nindent 4 }}
spec:
  domains:
  {{- range .Values.ingress.domains }}
    - {{ . }}
  {{- end }}
{{- end }}
