apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  labels:
    {{- include "task-tracker.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_PASSWORD: {{ .Values.secret.dbPassword | quote }}
