apiVersion: v1
kind: Service
metadata:
  name: {{ include "task-tracker.fullname" . }}-postgres-headless
  labels:
    app: postgres
    {{- include "task-tracker.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    app: postgres
  ports:
  - port: {{ .Values.postgres.service.port }}
    targetPort: {{ .Values.postgres.service.port }}
