apiVersion: v1
kind: Service
metadata:
  name: {{ include "task-tracker.fullname" . }}-redis-headless
  labels:
    app: {{ include "task-tracker.fullname" . }}-redis
    {{- include "task-tracker.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    app: {{ include "task-tracker.fullname" . }}-redis
  ports:
  - port: {{ .Values.redis.service.port }}
    targetPort: {{ .Values.redis.service.port }}
