apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "task-tracker.fullname" . }}-redis
  labels:
    app: redis
    {{- include "task-tracker.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  serviceName: {{ include "task-tracker.fullname" . }}-redis-headless
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
        ports:
        - containerPort: {{ .Values.redis.service.port }}
        resources:
          {{- toYaml .Values.redis.resources | nindent 10 }}
        volumeMounts:
        - name: redis-data
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: redis-data
    spec:
      accessModes:
      - {{ .Values.redis.storage.accessMode }}
      resources:
        requests:
          storage: {{ .Values.redis.storage.size }}
